services:
  - type: web
    name: checkar
    env: php
    buildCommand: "echo 'Build step'"
    startCommand: "php -S 0.0.0.0:80 -t public"
    envVars:
      - key: DB_HOST
        value: dpg-cq82v988fa8c738ccl1g-a
      - key: DB_NAME
        value: checkardb
      - key: DB_USER
        value: checkardb_user
      - key: DB_PASSWORD
        value: wzqgbNgdjPi3S3EgOQi0REKEMomdZxjk
