services:
  - type: web
    name: my-php-app
    env: php
    buildCommand: ""
    startCommand: "./start-php.sh"
    envVars:
      - key: DB_HOST
        value: dpg-cq82v988fa8c738ccl1g-a
      - key: DB_NAME
        value: checkardb
      - key: DB_USER
        value: checkardb_user
      - key: DB_PASSWORD
        value: wzqgbNgdjPi3S3EgOQi0REKEMomdZxjk
